### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by digitaldonkey** [spotify/mkdocs-monorepo-plugin#3]
I tried to add the plugin to mkdocs-material and locally. I get an error on live reaload changes:

```
[E 191011 14:40:27 ioloop:909] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/site-packages/livereload-2.6.1-py3.6.egg/livereload/handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python3.6/site-packages/livereload-2.6.1-py3.6.egg/livereload/watcher.py", line 94, in examine
        if self.is_changed(path, item['ignore']):
      File "/usr/local/lib/python3.6/site-packages/livereload-2.6.1-py3.6.egg/livereload/watcher.py", line 121, in is_changed
        if os.path.isfile(path):
      File "/usr/local/lib/python3.6/genericpath.py", line 30, in isfile
        st = os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```
Sorry in advance if my question is be stupid. I'm not a python developer.

**Comment by digitaldonkey** [comment]
Disappeared for unknown reason.

**Comment by bih** [comment]
@digitaldonkey Sorry to hear that! If you can reproduce it, please open up a new issue because we would happily fix this!

**Comment by digitaldonkey** [comment]
Learned: it happens when I request a page which is not in nav ^^
